# '''FOR THE POSTGRES, QDRANT, AND REDIS SERVICES
# This docker-compose file sets up a PostgreSQL database, a Qdrant vector database, and a Redis cache.


version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: palm_mind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334" # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  qdrant_data: